### ISSUE TITLE
Incorrect code background color

### ISSUE THREAD

**Issue by aoli-al** [janraasch/hugo-bearblog#114]
### Describe the bug

I noticed that the code background color is black on the example side. 

<img width="780" alt="Image" src="https://github.com/user-attachments/assets/5993957e-2275-416f-af3d-8d5f5b9f48b3" />

```css
element.style {
    color: #f8f8f2;
    background-color: #272822;
    -moz-tab-size: 4;
    -o-tab-size: 4;
    tab-size: 4;
}
```

Should the color value be: #f2f2f2 instead?

### Steps to reproduce

Goto https://janraasch.github.io/hugo-bearblog/markdown-syntax-guide/ and check the `Code Block` section. 

### Expected behavior

Original bear blog style:

<img width="765" alt="Image" src="https://github.com/user-attachments/assets/3895679c-d9c7-4dee-a131-4cf60b184b5e" />

### Hugo version

unknown
